version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo $CONTEXT_ENV
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo $PROJECT_ENV
      - run: echo $CONTEXT_ENV
      
workflows:
  version: 2
  workflow:
   jobs:
     - build:
         context: forked-project
     - hold:
         type: approval
         requires:
           - build
     - deploy:
         context: forked-project
         requires:
           - hold

